# Generated by Django 4.1.1 on 2022-10-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='Doctor_Name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='Patient_Name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='Time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
