# Generated by Django 4.1.1 on 2022-09-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('IT Equipment', 'IT Equipment'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Stationary', 'Stationary'), ('Beverages', 'Beverages'), ('Biscuits', 'Biscuits'), ('Bakery Products', 'Bakery Products'), ('Frozen Food', 'Frozen Food'), ('Personal Care', 'Personal Care'), ('Dairy', 'Dairy')], max_length=50, null=True)),
                ('Product_ID', models.CharField(blank=True, max_length=12)),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('unit_price', models.FloatField(blank=True, default='0.0', null=True)),
                ('selling_price', models.FloatField(blank=True, default='0.0', null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_to', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('initial_inserted', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
            ],
        ),
    ]
