# Generated by Django 4.1.1 on 2022-09-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='issue_to',
            new_name='Medicine_name',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='selling_price',
            new_name='Net_price',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='issue_by',
            new_name='Vendor',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='issue_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='receive_by',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='unit_price',
        ),
    ]
