# Generated by Django 4.1.1 on 2022-10-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20220909_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='BarCode',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
