# Generated by Django 4.1.1 on 2022-10-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_inventory_net_price_alter_inventory_product_id'),
        ('Inventory', '0004_inventory_barcode'),
    ]

    operations = [
    ]
