# Generated by Django 3.2.6 on 2022-09-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('speciality', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('phone', models.CharField(max_length=120)),
                ('dob', models.DateField()),
                ('NIC', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=220)),
                ('qr', models.CharField(max_length=200)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
